channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - brian2
  - cudatoolkit
  - matplotlib
  - openblas
  - numba
  - numpy
  - pandas
  - python>=3.8
  - pytorch
  - scipy
  - torchvision
  - tqdm
  - sphinx
  - nbsphinx
  - recommonmark
  - pandoc
  - pytest>=6.0
  - pytest-xdist
  - matplotlib
  - pip
  - pip:
      - jax
      - jaxlib
